# 1. Veritabanı Bağlantı Adresi (URL)
# jdbc:postgresql:// -> PostgreSQL sürücüsünü kullanacağımızı belirtir.
# localhost:5432 -> Veritabanının senin kendi bilgisayarında ve varsayılan 5432 portunda çalıştığını söyler.
# /antrenman_kocum -> pgAdmin'de oluşturduğumuz veritabanının birebir ismi.
spring.datasource.url=jdbc:postgresql://localhost:5432/antrenman_kocum

# 2. Veritabanı Kullanıcı Adı
# PostgreSQL kurulurken varsayılan olarak gelen ana kullanıcı adıdır. pgAdmin'de de gördüğün gibi "postgres" olarak kalmalı.
spring.datasource.username=postgres

# 3. Veritabanı Şifresi
# PostgreSQL'i bilgisayarına kurarken belirlediğin kendi kişisel şifreni buraya yaz.
spring.datasource.password=123456

# 4. Hibernate DDL Stratejisi (En Kritik Ayar!)
# Normalde burası 'update' veya 'create' yapılır ve Java koduna göre tabloları otomatik oluşturur.
# Ancak biz tabloları ve devasa veri setimizi pgAdmin'de elle yüklediğimiz için burayı 'validate' yapıyoruz.
# 'validate' ayarı: Proje açılırken Java sınıfları ile PostgreSQL'deki tabloları kıyaslar, uyuşuyorsa projeyi başlatır. Veritabanındaki tek bir veriye bile zarar vermez, korur.
spring.jpa.hibernate.ddl-auto=validate

# 5. SQL Sorgularını Konsolda Gösterme
# True yapıldığında, Spring Boot'un arka planda veritabanına attığı tüm SELECT, INSERT sorgularını VS Code terminalinde canlı olarak görmemizi sağlar. Hata ayıklarken (debugging) işimizi çok kolaylaştırır.
spring.jpa.show-sql=true

# 6. SQL Diyalekti
# Hibernate'e, arka planda sorguları oluştururken PostgreSQL 15/16 dil kurallarına (sözdizimine) uygun kararlar almasını söyler.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 7. Karakter Kodlaması
# Uygulama genelinde Türkçe karakterlerin (ş, ç, ğ, ı, ü, ö) bozulmadan aktarılmasını zorunlu kılar.
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true